//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilConvWpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilConvWpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian translation by sstanev.
        /// </summary>
        internal static string AboutBoxBulgarianTranslation {
            get {
                return ResourceManager.GetString("AboutBoxBulgarianTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2011 Sergey “SnakE” Gromov.
        /// </summary>
        internal static string AboutBoxCopyright {
            get {
                return ResourceManager.GetString("AboutBoxCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed for.
        /// </summary>
        internal static string AboutBoxDevelopedFor {
            get {
                return ResourceManager.GetString("AboutBoxDevelopedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software uses icons by Mark James.
        /// </summary>
        internal static string AboutBoxIconsBy {
            get {
                return ResourceManager.GetString("AboutBoxIconsBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fil Converter.
        /// </summary>
        internal static string AboutBoxProgramTitle {
            get {
                return ResourceManager.GetString("AboutBoxProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutBoxTitle {
            get {
                return ResourceManager.GetString("AboutBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill colors.
        /// </summary>
        internal static string Apple2ColorFillToggleTooltip {
            get {
                return ResourceManager.GetString("Apple2ColorFillToggleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTSC TV emulation.
        /// </summary>
        internal static string Apple2NtscModeToggleTooltip {
            get {
                return ResourceManager.GetString("Apple2NtscModeToggleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European (PAL)/American (NTSC) palette.
        /// </summary>
        internal static string Apple2PaletteToggleTooltip {
            get {
                return ResourceManager.GetString("Apple2PaletteToggleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple ][.
        /// </summary>
        internal static string Apple2ToolBarTitle {
            get {
                return ResourceManager.GetString("Apple2ToolBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native display proportions.
        /// </summary>
        internal static string AspectToggleTooltip {
            get {
                return ResourceManager.GetString("AspectToggleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rgb dithering.
        /// </summary>
        internal static string ColorDitherToggleTooltip {
            get {
                return ResourceManager.GetString("ColorDitherToggleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding:.
        /// </summary>
        internal static string EncodingToolbarTitle {
            get {
                return ResourceManager.GetString("EncodingToolbarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorMessageBoxTitle {
            get {
                return ResourceManager.GetString("ErrorMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string FileFormatNameAll {
            get {
                return ResourceManager.GetString("FileFormatNameAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Supported.
        /// </summary>
        internal static string FileFormatNameAllSupported {
            get {
                return ResourceManager.GetString("FileFormatNameAllSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bmp.
        /// </summary>
        internal static string FileFormatNameBmp {
            get {
                return ResourceManager.GetString("FileFormatNameBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fil.
        /// </summary>
        internal static string FileFormatNameFil {
            get {
                return ResourceManager.GetString("FileFormatNameFil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gif.
        /// </summary>
        internal static string FileFormatNameGif {
            get {
                return ResourceManager.GetString("FileFormatNameGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jpeg.
        /// </summary>
        internal static string FileFormatNameJpeg {
            get {
                return ResourceManager.GetString("FileFormatNameJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picler.
        /// </summary>
        internal static string FileFormatNamePicler {
            get {
                return ResourceManager.GetString("FileFormatNamePicler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Png.
        /// </summary>
        internal static string FileFormatNamePng {
            get {
                return ResourceManager.GetString("FileFormatNamePng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scr.
        /// </summary>
        internal static string FileFormatNameScr {
            get {
                return ResourceManager.GetString("FileFormatNameScr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiff.
        /// </summary>
        internal static string FileFormatNameTiff {
            get {
                return ResourceManager.GetString("FileFormatNameTiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple ][ Hi-Res.
        /// </summary>
        internal static string FormatNameApple2HiRes {
            get {
                return ResourceManager.GetString("FormatNameApple2HiRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple ][ Double Hi-Res.
        /// </summary>
        internal static string FormatNameApple2DoubleHiRes {
            get {
                return ResourceManager.GetString("FormatNameApple2DoubleHiRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple ][ Double Lo-Res.
        /// </summary>
        internal static string FormatNameApple2DoubleLoRes {
            get {
                return ResourceManager.GetString("FormatNameApple2DoubleLoRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple ][ Lo-Res.
        /// </summary>
        internal static string FormatNameApple2LoRes {
            get {
                return ResourceManager.GetString("FormatNameApple2LoRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMGR 128x256x16.
        /// </summary>
        internal static string FormatNameAgatCGSRDV {
            get {
                return ResourceManager.GetString("FormatNameAgatCGSRDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR7.
        /// </summary>
        internal static string FormatNameAgatCGNR {
            get {
                return ResourceManager.GetString("FormatNameAgatCGNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HGR.
        /// </summary>
        internal static string FormatNameAgatMGVR {
            get {
                return ResourceManager.GetString("FormatNameAgatMGVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HGR9.
        /// </summary>
        internal static string FormatNameAgatMGDP {
            get {
                return ResourceManager.GetString("FormatNameAgatMGDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGR.
        /// </summary>
        internal static string FormatNameAgatCGSR {
            get {
                return ResourceManager.GetString("FormatNameAgatCGSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGR9.
        /// </summary>
        internal static string FormatNameAgatCGVR {
            get {
                return ResourceManager.GetString("FormatNameAgatCGVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string FormatNameOriginal {
            get {
                return ResourceManager.GetString("FormatNameOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picler (bol).
        /// </summary>
        internal static string FormatNamePicler {
            get {
                return ResourceManager.GetString("FormatNamePicler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZX Spectrum.
        /// </summary>
        internal static string FormatNameSpectrum {
            get {
                return ResourceManager.GetString("FormatNameSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original:.
        /// </summary>
        internal static string LeftPreviewDefaultTitle {
            get {
                return ResourceManager.GetString("LeftPreviewDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fil Converter.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        internal static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        internal static string MenuFileOpen {
            get {
                return ResourceManager.GetString("MenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        internal static string MenuFileSaveAs {
            get {
                return ResourceManager.GetString("MenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        internal static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language.
        /// </summary>
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Auto.
        /// </summary>
        internal static string MenuLanguageAuto {
            get {
                return ResourceManager.GetString("MenuLanguageAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Български (_bg).
        /// </summary>
        internal static string MenuLanguageBulgarian {
            get {
                return ResourceManager.GetString("MenuLanguageBulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (_en).
        /// </summary>
        internal static string MenuLanguageEnglish {
            get {
                return ResourceManager.GetString("MenuLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский (_ru).
        /// </summary>
        internal static string MenuLanguageRussian {
            get {
                return ResourceManager.GetString("MenuLanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkButtonTitle {
            get {
                return ResourceManager.GetString("OkButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit window.
        /// </summary>
        internal static string PreviewPictureScaleFitWindow {
            get {
                return ResourceManager.GetString("PreviewPictureScaleFitWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview:.
        /// </summary>
        internal static string RightPreviewDefaultTitle {
            get {
                return ResourceManager.GetString("RightPreviewDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load image “{0}”: {1}.
        /// </summary>
        internal static string UnableToLoadFileError {
            get {
                return ResourceManager.GetString("UnableToLoadFileError", resourceCulture);
            }
        }
    }
}
